apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: novalink-services
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - lab3
      - default
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - users-service
          - products-service
          - orders-service
          - notifications-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s