# Hooks para pre-commit: pruebas unitarias y validaciones de código
repos:
    # Hooks para eliminar espacios en blanco, corregir el final de archivos y validar YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

    # Hooks para analisis de código Python: errorees sintácticos, malas prácticas y problemas de estilo
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

    # Hooks para formateo de código Python: para formato general y legibilidad uniforme (estilo de código)
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

    # Hooks para ordenar los imports en los archivos Python
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort

    # Hooks para detectar información sensible en el código (contraseñas, tokens, claves)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

    # Hooks para validar que las funciones y archivos Python tengan documentación estilo docstrings
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Check Python docstrings
        additional_dependencies: []

    # Hooks para ejecutar pruebas unitarias con pytest en el directorio Backend/test
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: pytest Backend/test/
        language: system
        pass_filenames: false