name: Deploy Auth Service

on:
  push:
    paths:
      - "services/auth-service/**"
      - ".github/workflows/deploy-auth.yml"

jobs:
  build-auth-service:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build auth-service image
        run: docker build -t auth-service:latest ./Backend/services/auth-service

      - name: Load image into Minikube
        run: minikube image load auth-service:latest

      - name: Deploy auth-service to Minikube
        run: |
          kubectl config use-context minikube
          kubectl apply -f ./Backend/k8s/auth-service.yaml

      - name: Restart auth-service deployment
        run: |
          kubectl rollout restart deployment/auth-service
          kubectl rollout status deployment/auth-service
